---

- name: make env file
  template:
    src: env-file.template
    dest: "{{ dest }}"
    owner: "{{ template_options['owner'] | default(omit) }}"
    group: "{{ template_options['backup'] | default(omit) }}"
    mode: "{{ template_options['backup'] | default(omit) }}"
    backup: "{{ template_options['backup'] | default(omit) }}"
    force: "{{ template_options['force'] | default(omit) }}"
    validate: "{{ template_options['validate'] | default(omit) }}"
    selevel: "{{ template_options['selevel'] | default(omit) }}"
    serole: "{{ template_options['serole'] | default(omit) }}"
    setype: "{{ template_options['setype'] | default(omit) }}"
    seuser: "{{ template_options['seuser'] | default(omit) }}"
  tags: [env-file]
