---

- name: make env file
  template:
    src: env-file.template
    dest: "{{ dest }}"
    owner: "{{ owner | default(omit) }}"
    group: "{{ group | default(omit) }}"
    mode: "{{ mode | default(omit) }}"
    backup: "{{ backup | default(omit) }}"
    force: "{{ force | default(omit) }}"
    validate: "{{ validate | default(omit) }}"
    selevel: "{{ selevel | default(omit) }}"
    serole: "{{ serole | default(omit) }}"
    setype: "{{ setype | default(omit) }}"
    seuser: "{{ seuser | default(omit) }}"
  tags: [env-file]
